### ISSUE TITLE
Extend @Path to lookup inherited properties

### ISSUE THREAD

**Issue by al-dexter** [unic/neba#147]
It would be nice to have something like this:

```
@Reference
@Path(name = "image/fileReference", lookupInherited = true)
private Asset asset;
```

to search the reference in the inherited properties too, not only in the current resource.

**Comment by olaf-otto** [comment]
Hi @al-dexter ,
I think this might be a more general use case - how about an @Inherited annotation?

However, there are various issues with inheritance. First of all, you have to traverse the parent structure and make assumptions about the page structure conventions ([cq:Page]/[jcr:content]/...) to build an inheritance of the form:

page/a/jcr:content/property
page/a/b/jcr:content/property

Then, can empty, but present property be inherited? If so, is there always a valid empty state for such properties e.g. boolean or complex types?

Regardless, could you prototype the desired behavior using a custom annotation with this: http://neba.io/apidocs/neba-api/io/neba/api/resourcemodels/AnnotatedFieldMapper.html?

Regards,
Olaf

**Comment by olaf-otto** [comment]
Since this would introduce AEM-specific hierarchy assumptions due to the special role of "cq:Page" nodes in the repository, I am closing this as won't fix for NEBA. However, I believe this would be well feasible with   a custom annotation + [custom field mapper](http://neba.io/apidocs/neba-api/io/neba/api/resourcemodels/AnnotatedFieldMapper.html).
