### ISSUE TITLE
Unable to @Reference DataSourcePool within a @Component/@Service

### ISSUE THREAD

**Issue by mattshurley** [unic/neba#214]
Hi,

I am trying to reference a handle to the com.day.commons.datasource.poolservice.DataSourcePool within a component but I am unable to do so, it just returns null.

@org.apache.felix.scr.annotations.Reference
private DataSourcePool dataSourcePool;

<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:mvc="http://www.springframework.org/schema/mvc"
       xmlns:bp="http://www.osgi.org/xmlns/blueprint/v1.0.0"
       xmlns:cm="http://www.eclipse.org/gemini/blueprint/schema/blueprint-compendium"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
   http://www.springframework.org/schema/beans/spring-beans-4.2.xsd
   http://www.osgi.org/xmlns/blueprint/v1.0.0
   http://www.osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd
   http://www.springframework.org/schema/context
   http://www.springframework.org/schema/context/spring-context-4.2.xsd
   http://www.springframework.org/schema/mvc
   http://www.springframework.org/schema/mvc/spring-mvc-4.2.xsd
   http://www.eclipse.org/gemini/blueprint/schema/blueprint-compendium
   http://www.eclipse.org/gemini/blueprint/schema/blueprint-compendium/gemini-blueprint-compendium.xsd">

    <context:component-scan base-package="com.xxx.yyy"/>

    <mvc:annotation-driven></mvc:annotation-driven>

**Comment by olaf-otto** [comment]
Hi @mattshurley,

Thanks for reaching out! NEBA works with Spring and Gemini Blueprint annotations, Since org.apache.felix.scr.annotations.Reference is an SCR annotation, it will only work for SCR components, not Spring beans. In order to reference the com.day.commons.datasource.poolservice.DataSourcePool OSGi service from a Spring bean, you can either import it in your blueprint XML or use the blueprint [@ServiceReference annotation](https://eclipse.org/gemini/blueprint/documentation/reference/2.1.0.RELEASE/html/service-registry.html#service-registry:annotations-vs-xml-declarations). Here is how that works:

## Importing the OSGI service in your blueprint XML
```
...
<bp:blueprint>
...
<bp:reference interface="com.day.commons.datasource.poolservice.DataSourcePool" id="datasourcePool"/>
</bp:blueprint>
```

Then, you can use @javax.annotation.Resource or @javax.Inject the service into your bean.

## Using the blueprint @ServiceReference annotation
Simply annotate your field with the org.eclipse.gemini.blueprint.extensions.annotation.ServiceReference annotation:

```
...
@ServiceReference
private DataSourcePool datasourcePool;
...
```

See also the [NEBA sample project](https://github.com/unic/neba-sample-project) for examples.

Hope that helps!
Olaf

**Comment by mattshurley** [comment]
I went with importing the OSGI service into the blueprint XML and it resolved the issue. Thanks!
