### ISSUE TITLE
Want to change /bin/mvc.do to /<my-custom-path>

### ISSUE THREAD

**Issue by kunnu** [unic/neba#246]
Hi, 

I want to change default context path to my owned path. Could you please let me know how to do this, may be through small piece of code.

Thanks,
Kunal

**Comment by olaf-otto** [comment]
Hi @kunnu!

You can easily do this with a [resource resolver mapping](https://sling.apache.org/documentation/the-sling-engine/mappings-for-resource-resolution.html)

For instance, in order to change the path from /bin/mvc.do to /controllers.do, add:

    /bin/mvc:/controllers

to the URL Mappings of the Apache Sling Resource Resolver Factory configuration.

Hope that helps!
Olaf

**Comment by kunnu** [comment]
Thanks Olaf! This works with .do extension. Can we remove .do too? I want only /comtrollers without .do.

**Comment by olaf-otto** [comment]
Hi kununu,
Good question - yes it does! I just tried it with the NEBA sample project. In this case, you need to configure a mapping of the form:

`/bin/mvc.do:/controllers`

Subsequently you can address your controllers e.g. using /controllers/myController.

Trivia: The extension is required to make Sling understand we are a servlet at /bin/mvc. For instance, /bin/mvc/myController would be a different servlet path from a Sling perspective, thus controller path and the dispatcher servlet path are separated with an extension.

**Comment by kunnu** [comment]
Thanks Olaf! Please ignore my last comment.
